"""Occupation families for the V2 corpus generator.

Deliberately broader than — and not aligned with — Forja's taxonomy: skill
strings mix taxonomy ids with free-form terms ("spring boot", "gerica
journalsystem"), titles include misleading variants, and requirement patterns
span every hard-constraint dimension. Certifications reference the taxonomy's
credential registry (legal credentials are a closed set by nature).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Family:
    key: str
    sector: str
    titles: tuple[str, ...]
    skills_core: tuple[str, ...]
    skills_extra: tuple[str, ...] = ()
    misleading_titles: tuple[str, ...] = ()          # sound like other families
    cert_options: tuple[tuple[str, ...], ...] = ((),)
    license_options: tuple = (None,)
    norwegian_options: tuple = ("B1", "B2", None)
    english_options: tuple = (None,)
    shift_options: tuple[tuple[str, ...], ...] = (("day",),)
    percent_options: tuple[int, ...] = (100,)
    salary_band: tuple[int, int] = (450_000, 600_000)
    physical_options: tuple[tuple[str, ...], ...] = ((),)
    overnight_choices: tuple[bool, ...] = (False,)
    work_modes: tuple[str, ...] = ("onsite",)
    min_years_options: tuple[float, ...] = (0, 2, 3)
    duty_phrases: tuple[str, ...] = ()
    employers: tuple[str, ...] = ()


F = Family

FAMILIES: dict[str, Family] = {f.key: f for f in [
    # ---------------- Helse ----------------
    F("sykepleier", "helse",
      titles=("Sykepleier", "Sykepleier sengepost", "Sykepleier poliklinikk", "Fagsykepleier"),
      misleading_titles=("Helsekonsulent",),
      skills_core=("klinisk sykepleie", "medikamenthandtering", "pasientveiledning"),
      skills_extra=("journalforing_dips", "palliativ_pleie", "triage", "sarstell"),
      cert_options=(("hpr_autorisasjon_sykepleier",),),
      norwegian_options=("C1",),
      shift_options=(("day",), ("day", "evening", "night", "weekend"), ("day", "evening", "weekend")),
      percent_options=(100, 80, 70),
      salary_band=(500_000, 590_000),
      duty_phrases=("Du følger opp pasienter gjennom hele forløpet.",
                    "Medikamenthåndtering og dokumentasjon er sentrale oppgaver.",
                    "Du samarbeider tett med lege og tverrfaglig team."),
      employers=("Helse Vest klinikk", "Diakonalt sykehus", "Kommunehelsetjenesten", "Privat klinikk")),
    F("helsefagarbeider", "helse",
      titles=("Helsefagarbeider", "Pleiemedarbeider", "Assistent i hjemmetjenesten", "Miljøarbeider omsorg"),
      skills_core=("helsefagarbeid", "stell og pleie", "dokumentasjon"),
      skills_extra=("gerica journalsystem", "forflytning", "miljoarbeid"),
      cert_options=(("autorisasjon_helsefagarbeider",), ()),
      norwegian_options=("B1", "B2"),
      shift_options=(("day",), ("day", "evening", "weekend"), ("day", "evening", "night", "weekend")),
      percent_options=(100, 80, 60),
      salary_band=(420_000, 500_000),
      physical_options=((), ("heavy_lifting",)),
      duty_phrases=("Du gir stell, omsorg og praktisk bistand til brukerne.",
                    "Dokumentasjon i journalsystemet inngår i hverdagen.",
                    "Du bidrar til gode dager for beboerne."),
      employers=("Kommunal omsorgstjeneste", "Omsorgsdrift", "Sykehjemsetaten", "Bo- og servicesenter")),
    F("legekontor", "helse",
      titles=("Medarbeider legekontor", "Helsesekretær-vikar", "Pasientkoordinator"),
      skills_core=("kundeservice", "dokumentasjon", "timebestilling"),
      skills_extra=("helsenorge-portal", "laboratorieprover", "sentralbord"),
      norwegian_options=("B2", "C1"),
      percent_options=(100, 80),
      salary_band=(430_000, 510_000),
      duty_phrases=("Du tar imot pasienter og administrerer timebøkene.",
                    "Enklere prøvetaking og forefallende kontorarbeid inngår."),
      employers=("Legegruppen", "Fastlegekontoret", "Helsehuset")),
    F("apotek", "helse",
      titles=("Apotekmedarbeider", "Apotektekniker", "Farmasøyt"),
      skills_core=("apotekteknikk", "kundeservice", "legemiddelhandtering"),
      skills_extra=("salg", "varepafylling", "resepthandtering"),
      cert_options=((), ("hpr_autorisasjon_farmasoyt",)),
      norwegian_options=("B1", "B2"),
      shift_options=(("day",), ("day", "weekend")),
      percent_options=(100, 80, 60),
      salary_band=(420_000, 620_000),
      duty_phrases=("Du veileder kunder i selvvalg og ved resepturen.",
                    "Nøyaktighet og faglig trygghet er avgjørende."),
      employers=("Apotekkjeden", "Sentrumsapoteket", "Sykehusapoteket")),
    F("ehelse_kundesuksess", "teknologi",
      titles=("Kundesuksessansvarlig e-helse", "Customer Success Manager helse", "Rådgiver e-helse"),
      skills_core=("kundesuksess", "kommunikasjon"),
      skills_extra=("klinisk sykepleie", "journalforing_dips", "crm_system", "opplaering"),
      norwegian_options=("B2", "C1"),
      work_modes=("hybrid", "onsite", "remote"),
      salary_band=(550_000, 680_000),
      min_years_options=(2, 3),
      duty_phrases=("Du hjelper helsevirksomheter å lykkes med løsningen vår.",
                    "Helsefaglig bakgrunn er et stort pluss i møte med klinikere."),
      employers=("MedTech Norge", "JournalPartner", "E-helseleverandøren")),

    # ---------------- Teknologi ----------------
    F("backend_dev", "teknologi",
      titles=("Backend-utvikler", "Senior backendutvikler", "Systemutvikler"),
      misleading_titles=("Utviklingsleder oppvekst",),
      skills_core=("java", "api_design", "postgresql"),
      skills_extra=("spring boot", "kubernetes", "microservices", "kafka", "go", "python"),
      norwegian_options=("B1", "B2", None),
      english_options=("B2", None),
      work_modes=("hybrid", "onsite", "remote"),
      salary_band=(700_000, 950_000),
      min_years_options=(2, 3, 5),
      duty_phrases=("Du bygger og drifter tjenester i produksjon.",
                    "Kodekvalitet og testdekning tas på alvor.",
                    "Teamet eier tjenestene sine ende til ende."),
      employers=("Fintech-huset", "Systemleverandøren", "Digitaliseringsetaten", "SaaS-selskapet")),
    F("frontend_dev", "teknologi",
      titles=("Frontend-utvikler", "Fullstack-utvikler"),
      skills_core=("typescript", "react", "css"),
      skills_extra=("next.js", "api_design", "design system", "webpack"),
      norwegian_options=("B2", None),
      english_options=("B2",),
      work_modes=("hybrid", "remote", "onsite"),
      salary_band=(650_000, 880_000),
      min_years_options=(2, 3),
      duty_phrases=("Du lager brukergrensesnitt med høye krav til kvalitet.",
                    "Universell utforming er en del av jobben."),
      employers=("Skyleverandøren", "Mediehuset digital", "Konsulentpartner")),
    F("devops_plattform", "teknologi",
      titles=("Plattformingeniør", "DevOps-ingeniør", "SRE"),
      skills_core=("kubernetes", "terraform", "ci_cd"),
      skills_extra=("aws", "azure", "linux", "observability", "gitops"),
      norwegian_options=("B2", None),
      english_options=("B2",),
      work_modes=("hybrid", "onsite"),
      salary_band=(750_000, 980_000),
      min_years_options=(3, 4, 5),
      duty_phrases=("Du bygger utviklerplattformen resten av huset står på.",
                    "Drift, beredskap og automatisering er kjernen."),
      employers=("Plattformselskapet", "Kraftkonsernet IT", "Banken teknologi")),
    F("data_analyst", "teknologi",
      titles=("Dataanalytiker", "Data Scientist", "Analytiker forretningsinnsikt"),
      misleading_titles=("Analytisk kjemiker",),
      skills_core=("dataanalyse", "sql", "python"),
      skills_extra=("powerbi", "maskinlaering", "statistikk", "dbt", "excel"),
      norwegian_options=("B2", None),
      english_options=("B2", None),
      work_modes=("hybrid", "onsite", "remote"),
      salary_band=(600_000, 850_000),
      min_years_options=(0, 2, 3, 5),
      duty_phrases=("Du gjør data om til beslutninger for forretningen.",
                    "Modellering, dashboards og analyser inngår i hverdagen."),
      employers=("Analysehuset", "Forsikringsselskapet", "Energikonsernet innsikt", "Handelskjeden data")),
    F("it_support", "teknologi",
      titles=("IT-supportkonsulent", "Servicedesk-medarbeider", "Førstelinje IT"),
      skills_core=("it_support", "kundeservice", "windows"),
      skills_extra=("nettverk_drift", "microsoft 365", "linux", "sakssystem"),
      norwegian_options=("B1", "B2"),
      shift_options=(("day",), ("day", "evening")),
      salary_band=(440_000, 560_000),
      min_years_options=(0, 1, 2),
      duty_phrases=("Du løser brukernes IT-problemer i første linje.",
                    "Serviceinnstilling teller like mye som teknikk.",
                    "Du dokumenterer løsninger i kunnskapsbasen."),
      employers=("Driftspartneren", "Kommunens IT-avdeling", "Servicedesken AS")),
    F("ux_designer", "teknologi",
      titles=("UX-designer", "Senior UX Designer", "Product Designer"),
      skills_core=("ux_design", "figma", "brukertesting"),
      skills_extra=("design system", "grafisk_design", "prototyping", "universell utforming"),
      norwegian_options=("B2", "B1", None),
      english_options=("B2", "C1"),
      work_modes=("hybrid", "onsite", "remote"),
      salary_band=(620_000, 820_000),
      min_years_options=(2, 3, 5),
      duty_phrases=("Du eier designprosessen fra innsikt til leveranse.",
                    "Brukertesting og designsystem er sentrale verktøy."),
      employers=("Designstudioet", "Fintech-scaleupen", "Offentlig digitalisering")),

    # ---------------- Bygg og anlegg ----------------
    F("bygg_ingenior", "bygg_anlegg",
      titles=("Konstruktør", "Byggingeniør konstruksjon", "Rådgivende ingeniør bygg"),
      skills_core=("konstruksjonsberegning", "autocad"),
      skills_extra=("betongkonstruksjoner", "stalkonstruksjoner", "etabs", "revit", "eurokoder"),
      norwegian_options=("B1", "B2", None),
      english_options=(None, "B2"),
      salary_band=(600_000, 780_000),
      min_years_options=(2, 3, 5),
      duty_phrases=("Du dimensjonerer bærende konstruksjoner i betong og stål.",
                    "Prosjektene spenner fra boligblokker til næringsbygg."),
      employers=("Rådgivende Ingeniører", "Prosjekteringshuset", "Entreprenørkonsernet teknikk")),
    F("teknisk_tegner", "bygg_anlegg",
      titles=("Teknisk tegner", "DAK-operatør", "BIM-tekniker"),
      skills_core=("teknisk_tegning", "autocad"),
      skills_extra=("revit", "armeringstegning", "bim"),
      norwegian_options=("B1", "B2"),
      salary_band=(500_000, 620_000),
      min_years_options=(0, 2),
      duty_phrases=("Du produserer arbeids- og detaljtegninger for prosjektene.",),
      employers=("Tegnekontoret", "Prosjekteringshuset")),
    F("byggeleder", "bygg_anlegg",
      titles=("Byggeleder", "Prosjektleder bygg", "Kalkulatør", "KS-ansvarlig bygg"),
      skills_core=("byggeledelse", "hms", "kalkulasjon"),
      skills_extra=("fremdriftsplanlegging", "kvalitetssikring_ks", "kontraktsoppfolging", "tomrerarbeid"),
      norwegian_options=("B2", "C1"),
      salary_band=(580_000, 760_000),
      overnight_choices=(False, False, True),
      min_years_options=(3, 5),
      duty_phrases=("Du styrer fremdrift, økonomi og HMS på byggeplassen.",
                    "Praktisk fagbakgrunn er høyt verdsatt."),
      employers=("Entreprenørkonsernet", "Boligbyggeren", "Byggherreombudet")),
    F("tomrer", "bygg_anlegg",
      titles=("Tømrer", "Snekker nybygg", "Tømrer rehabilitering"),
      skills_core=("tomrerarbeid", "presisjonsarbeid"),
      skills_extra=("kvalitetssikring_ks", "membranarbeid", "lafting"),
      cert_options=(("fagbrev_tomrer",), ()),
      norwegian_options=("B1",),
      salary_band=(480_000, 600_000),
      physical_options=(("heavy_lifting",), ("heavy_lifting", "working_at_heights")),
      overnight_choices=(False, True),
      min_years_options=(2, 3),
      duty_phrases=("Nybygg og rehabilitering med høye krav til utførelse.",
                    "Fysisk arbeid i alle faser av byggeprosessen."),
      employers=("Byggmesterfirmaet", "Totalentreprenøren", "Hyttebyggeren")),
    F("elektriker", "bygg_anlegg",
      titles=("Elektriker", "Serviceelektriker", "Elektromontør"),
      skills_core=("elektro_installasjon", "feilsoking_elektro"),
      skills_extra=("internkontroll", "ekom", "smarthus"),
      cert_options=(("fagbrev_elektriker", "fse_lavspenning"), ("fagbrev_elektriker",)),
      license_options=(None, "B"),
      norwegian_options=("B1",),
      salary_band=(540_000, 650_000),
      physical_options=(("heavy_lifting",), ("heavy_lifting", "working_at_heights"), ()),
      overnight_choices=(False, True),
      min_years_options=(2, 3, 5),
      duty_phrases=("Installasjon og service i bolig og næring.",
                    "Selvstendig feilsøking hos kunde."),
      employers=("Installasjonspartner", "Elektrogruppen", "Energiselskapet montasje")),
    F("elektro_kontor", "energi",
      titles=("Planlegger elektro", "Saksbehandler elsikkerhet", "KS/HMS-koordinator elektro"),
      skills_core=("internkontroll", "dokumentasjon"),
      skills_extra=("elektro_installasjon", "kvalitetssikring_ks", "hms", "feilsoking_elektro", "teknisk_tegning"),
      cert_options=(("fagbrev_elektriker",), ()),
      norwegian_options=("B2",),
      work_modes=("onsite", "hybrid"),
      salary_band=(580_000, 700_000),
      min_years_options=(3, 5),
      duty_phrases=("Kontorrolle der fagbakgrunn fra elektro er gull verdt.",
                    "Du planlegger, dokumenterer og følger opp anlegg."),
      employers=("Nettselskapet", "Elsikkerhet Norge", "Installasjonskonsernet stab")),
    F("automasjon", "industri",
      titles=("Automasjonstekniker", "Automatiker", "Instrumenttekniker"),
      skills_core=("automasjon", "plc"),
      skills_extra=("feilsoking_elektro", "robotics", "scada"),
      cert_options=(("fagbrev_elektriker",), ()),
      norwegian_options=("B1",),
      shift_options=(("day",), ("day", "night"), ("day", "evening", "night", "weekend")),
      salary_band=(560_000, 700_000),
      min_years_options=(2, 3),
      duty_phrases=("Vedlikehold og forbedring av automatiserte linjer.",),
      employers=("Prosessindustrien", "Næringsmiddelfabrikken", "Robotintegratøren")),
    F("prosessoperator", "industri",
      titles=("Prosessoperatør", "Driftsoperatør landanlegg", "Prosesstekniker offshore"),
      skills_core=("prosessoperator_drift", "hms"),
      skills_extra=("internkontroll", "dokumentasjon", "kontrollrom"),
      cert_options=((), ("gsk_sikkerhetskurs",)),
      norwegian_options=("B1", "B2"),
      shift_options=(("day", "night"), ("day", "evening", "night", "weekend"), ("day",)),
      salary_band=(600_000, 820_000),
      overnight_choices=(False, True),
      min_years_options=(2, 3, 5),
      duty_phrases=("Drift og overvåking av prosessanlegget.",
                    "HMS står først i alt vi gjør."),
      employers=("Landanlegget", "Operatørselskapet", "Prosessindustrien Vest")),
    F("maskinforer", "bygg_anlegg",
      titles=("Maskinfører", "Anleggsmaskinfører"),
      skills_core=("maskinkjoring_anlegg",),
      skills_extra=("lastsikring", "hms", "masseforflytning"),
      cert_options=(("maskinforerbevis",),),
      norwegian_options=("B1",),
      salary_band=(500_000, 620_000),
      overnight_choices=(False, True),
      min_years_options=(2, 3),
      duty_phrases=("Graving, planering og masseforflytning på prosjekt.",),
      employers=("Anleggsdrift", "Maskinentreprenøren")),
    F("sveiser", "industri",
      titles=("Sveiser", "Platearbeider/sveiser"),
      skills_core=("sveising",),
      skills_extra=("hms", "mig/mag", "tig"),
      norwegian_options=("B1", "A2"),
      shift_options=(("day",), ("day", "evening")),
      salary_band=(480_000, 600_000),
      physical_options=(("heavy_lifting",),),
      min_years_options=(2, 3),
      duty_phrases=("Sveising av stålkomponenter etter tegning.",),
      employers=("Mekanisk verksted", "Skipsverftet")),
    F("byggesak", "offentlig",
      titles=("Byggesaksbehandler", "Saksbehandler plan og bygg"),
      skills_core=("byggesak", "saksbehandling"),
      skills_extra=("teknisk_tegning", "forvaltningsrett"),
      norwegian_options=("C1",),
      work_modes=("onsite", "hybrid"),
      salary_band=(550_000, 650_000),
      min_years_options=(2, 3),
      duty_phrases=("Behandling av søknader etter plan- og bygningsloven.",),
      employers=("Kommunen byggesak", "Fylkesadministrasjonen")),

    # ---------------- Handel og service ----------------
    F("butikksjef", "handel",
      titles=("Butikksjef", "Varehussjef", "Assisterende butikksjef"),
      misleading_titles=("Salgssjef digitale flater",),
      skills_core=("butikkdrift", "personalledelse", "budsjettansvar"),
      skills_extra=("varelogistikk", "innkjop", "salg", "vaktplanlegging"),
      norwegian_options=("B2",),
      shift_options=(("day", "weekend"), ("day", "evening", "weekend")),
      salary_band=(540_000, 700_000),
      min_years_options=(3, 5, 8),
      duty_phrases=("Fullt resultat- og personalansvar for butikken.",
                    "Du bygger et lag som leverer på kundeopplevelse."),
      employers=("Handelskjeden", "Elektrovarehuset", "Byggevarehuset", "Interiørkjeden")),
    F("butikkmedarbeider", "handel",
      titles=("Butikkmedarbeider", "Salgsmedarbeider butikk"),
      skills_core=("kundeservice", "salg"),
      skills_extra=("varepafylling", "kasse"),
      norwegian_options=("B1",),
      shift_options=(("day", "weekend"), ("day", "evening", "weekend")),
      percent_options=(100, 80, 60, 40),
      salary_band=(400_000, 470_000),
      min_years_options=(0, 1),
      duty_phrases=("Kundemøter, kasse og varetrykk i høyt tempo.",),
      employers=("Sportskjeden", "Dagligvarebutikken", "Klesbutikken")),
    F("kontaktsenter", "handel",
      titles=("Kundeservicemedarbeider", "Kundeservicesjef", "Teamleder kundesenter"),
      skills_core=("kundeservice", "crm_system"),
      skills_extra=("personalledelse", "opplaering_ansatte", "salg"),
      norwegian_options=("B2",),
      shift_options=(("day",), ("day", "evening")),
      salary_band=(440_000, 620_000),
      min_years_options=(0, 2, 5),
      duty_phrases=("Du løser kundehenvendelser på telefon, chat og e-post.",
                    "Målbar kundetilfredshet styrer hverdagen."),
      employers=("Kraftselskapet kundesenter", "Teleoperatøren", "Forsikringskundeservice")),
    F("salgsleder", "handel",
      titles=("Salgssjef B2B", "Key Account Manager", "Salgsleder SaaS"),
      skills_core=("salg", "crm_system", "budsjettansvar"),
      skills_extra=("teamledelse", "kundeoppfolging", "forhandling"),
      norwegian_options=("B2", "C1"),
      license_options=(None, "B"),
      work_modes=("onsite", "hybrid"),
      salary_band=(620_000, 900_000),
      overnight_choices=(False, True),
      min_years_options=(3, 5),
      duty_phrases=("Resultatansvar for porteføljen og pipeline-disiplin i CRM.",
                    "Du leder salgsarbeidet mot nye og eksisterende kunder."),
      employers=("Programvarehuset", "Grossisten B2B", "Teknologileverandøren")),
    F("resepsjon", "handel",
      titles=("Resepsjonist", "Front office-medarbeider", "Resepsjonsleder"),
      skills_core=("resepsjonsarbeid", "kundeservice"),
      skills_extra=("opera pms", "booking", "personalledelse", "vaktplanlegging"),
      norwegian_options=("B2",),
      english_options=("B1", "B2"),
      shift_options=(("day",), ("day", "evening", "weekend"), ("day", "evening", "night", "weekend")),
      percent_options=(100, 80),
      salary_band=(420_000, 560_000),
      min_years_options=(0, 2, 5),
      duty_phrases=("Du er husets ansikt utad ved ankomst og avreise.",
                    "Vaktene styrer belegg, booking og gjesteopplevelse."),
      employers=("Sentrumshotellet", "Konferansehotellet", "Kontorhuset resepsjon")),
    F("vekter", "handel",
      titles=("Vekter", "Sikkerhetsvakt kjøpesenter"),
      skills_core=("vakthold", "kundeservice"),
      cert_options=(("vekterutdanning",),),
      norwegian_options=("B2",),
      shift_options=(("day", "evening", "weekend"), ("day", "evening", "night", "weekend")),
      salary_band=(420_000, 520_000),
      min_years_options=(0, 1),
      duty_phrases=("Forebyggende vakthold og god publikumshåndtering.",),
      employers=("Sikkerhetsselskapet", "Vaktpartner")),
    F("frisor", "handel",
      titles=("Frisør", "Frisør med kundeportefølje"),
      skills_core=("frisering", "kundeservice"),
      cert_options=(("svennebrev_frisor",),),
      norwegian_options=("B2",),
      shift_options=(("day", "weekend"),),
      salary_band=(400_000, 480_000),
      physical_options=(("prolonged_standing",),),
      min_years_options=(1, 2),
      duty_phrases=("Klipp, farge og styling i travel salong.",),
      employers=("Salongkjeden", "Sentrumssalongen")),
    F("kokk", "handel",
      titles=("Kokk", "Kokk institusjon", "Kokk offshore"),
      skills_core=("matlaging", "hms"),
      skills_extra=("meny-planlegging", "ikke-allergener"),
      cert_options=(("fagbrev_kokk",), ()),
      norwegian_options=("B1",),
      shift_options=(("day",), ("day", "evening", "weekend")),
      salary_band=(430_000, 620_000),
      physical_options=(("prolonged_standing",),),
      overnight_choices=(False, True),
      min_years_options=(2, 3),
      duty_phrases=("Du lager mat fra bunnen i høyt tempo.",),
      employers=("Kantineoperatøren", "Institusjonskjøkkenet", "Forpleiningsselskapet")),
    F("renhold", "industri",
      titles=("Renholdsoperatør", "Renholder næringsbygg"),
      skills_core=("renhold",),
      norwegian_options=("A2", "B1"),
      percent_options=(100, 80, 60),
      salary_band=(390_000, 440_000),
      physical_options=(("prolonged_standing",),),
      min_years_options=(0,),
      duty_phrases=("Daglig renhold etter kvalitetsstandard INSTA 800.",),
      employers=("Servicepartneren", "Renholdsbyrået")),

    # ---------------- Økonomi / administrasjon ----------------
    F("regnskap", "finans",
      titles=("Regnskapskonsulent", "Regnskapsfører", "Autorisert regnskapsfører"),
      skills_core=("regnskap", "visma"),
      skills_extra=("arsoppgjor", "lonn", "mva", "tripletex", "poweroffice"),
      cert_options=((), ("autorisert_regnskapsforer",)),
      norwegian_options=("B2",),
      work_modes=("onsite", "hybrid"),
      percent_options=(100, 80, 70, 60),
      salary_band=(520_000, 680_000),
      min_years_options=(2, 3, 5),
      duty_phrases=("Løpende føring og periodeavslutning for kundeporteføljen.",
                    "Du er kundens rådgiver i det daglige."),
      employers=("Regnskapshuset", "Økonomitjenester AS", "Byrået Tall & Råd")),
    F("controller", "finans",
      titles=("Controller", "Konserncontroller", "Business controller"),
      misleading_titles=("Dokumentcontroller bygg",),
      skills_core=("controlling", "excel", "rapportering"),
      skills_extra=("ifrs", "konsolidering", "sap", "powerbi", "prognoser"),
      norwegian_options=("B2",),
      work_modes=("onsite", "hybrid"),
      percent_options=(100, 80, 60),
      salary_band=(620_000, 850_000),
      min_years_options=(3, 5),
      duty_phrases=("Måneds- og kvartalsrapportering med korte frister.",
                    "Du utfordrer tallene og forretningen."),
      employers=("Industrikonsernet", "Eiendomsselskapet", "Mediehuset økonomi", "Stiftelsen")),
    F("lonn_hr", "finans",
      titles=("Lønnsmedarbeider", "Lønningsansvarlig", "HR- og lønnskonsulent"),
      skills_core=("lonn", "regnskap"),
      skills_extra=("visma", "excel", "turnustillegg", "a-melding"),
      norwegian_options=("B2",),
      percent_options=(100, 80),
      salary_band=(520_000, 640_000),
      min_years_options=(2, 3),
      duty_phrases=("Du kjører lønn for flere hundre ansatte hver måned.",),
      employers=("Lønnssenteret", "Omsorgskonsernet stab", "Handelsgruppen HR")),
    F("okonomi_junior", "finans",
      titles=("Regnskapsassistent", "Økonomimedarbeider", "Junior controller"),
      skills_core=("excel", "regnskap"),
      skills_extra=("fakturering", "kundeservice", "powerbi"),
      norwegian_options=("B2",),
      percent_options=(100, 80),
      salary_band=(430_000, 520_000),
      min_years_options=(0, 1),
      duty_phrases=("Fakturering, avstemminger og bilagsføring under veiledning.",
                    "Perfekt startjobb for nyutdannede økonomer."),
      employers=("Økonomiavdelingen", "Shared services-senteret", "Regnskapshuset junior")),
    F("hr_radgiver", "offentlig",
      titles=("HR-rådgiver", "Rekrutteringsrådgiver", "Personalkonsulent"),
      skills_core=("rekruttering", "saksbehandling"),
      skills_extra=("kommunikasjon", "personalledelse", "arbeidsrett"),
      norwegian_options=("C1",),
      work_modes=("onsite", "hybrid"),
      salary_band=(540_000, 660_000),
      min_years_options=(2, 3),
      duty_phrases=("Du støtter lederne i rekruttering og personalsaker.",),
      employers=("Kommunen HR", "Helseforetaket personal", "Direktoratet")),
    F("jurist", "finans",
      titles=("Advokatfullmektig", "Juridisk rådgiver"),
      skills_core=("juridisk_radgivning", "saksbehandling"),
      norwegian_options=("C1",),
      english_options=(None, "B2"),
      salary_band=(620_000, 850_000),
      min_years_options=(0, 2),
      duty_phrases=("Rådgivning og tvisteløsning for næringslivsklienter.",),
      employers=("Advokatfirmaet", "Juridisk avdeling konsern")),

    # ---------------- Utdanning / innhold ----------------
    F("laerer", "utdanning",
      titles=("Lektor", "Lærer ungdomstrinn", "Adjunkt"),
      skills_core=("undervisning", "klasseledelse"),
      skills_extra=("laereplanarbeid", "digital_laering", "vurdering"),
      cert_options=(("ppu_pedagogisk_utdanning",),),
      norwegian_options=("C1",),
      percent_options=(100, 80),
      salary_band=(540_000, 660_000),
      duty_phrases=("Undervisning, vurdering og tett elevoppfølging.",),
      employers=("Kommunen skole", "Ungdomsskolen", "Videregående skole")),
    F("barnehage", "utdanning",
      titles=("Barnehageassistent", "Fagarbeider barnehage", "Pedagogisk leder"),
      skills_core=("pedagogisk_arbeid_barn",),
      skills_extra=("foreldresamarbeid", "spesialpedagogikk"),
      cert_options=((), ("barnehagelarerutdanning",)),
      norwegian_options=("B1", "B2"),
      percent_options=(100, 80, 60),
      salary_band=(400_000, 560_000),
      duty_phrases=("Omsorg, lek og læring for barna hver dag.",),
      employers=("Barnehagestiftelsen", "Kommunale barnehager", "Friluftsbarnehagen")),
    F("edtech_innhold", "teknologi",
      titles=("Innholdsutvikler læremidler", "Læremiddelforfatter", "Fagredaktør digital læring"),
      skills_core=("innholdsproduksjon", "laereplanarbeid"),
      skills_extra=("undervisning", "digital_laering", "manusarbeid"),
      norwegian_options=("C1",),
      english_options=(None, "C1"),
      work_modes=("remote", "hybrid", "onsite"),
      salary_band=(550_000, 660_000),
      min_years_options=(2, 3),
      duty_phrases=("Du utvikler digitale læremidler lærere faktisk vil bruke.",
                    "Lærerbakgrunn er sterkt ønsket."),
      employers=("Læremiddelforlaget", "Edtech-selskapet", "Undervisningsforlaget")),
    F("kursutvikler", "utdanning",
      titles=("Kursutvikler", "Fagansvarlig opplæring", "Instructional designer"),
      skills_core=("kursutvikling", "formidling"),
      skills_extra=("digital_laering", "innholdsproduksjon"),
      norwegian_options=("B2", "C1"),
      work_modes=("onsite", "hybrid"),
      percent_options=(100, 80, 60),
      salary_band=(500_000, 620_000),
      min_years_options=(2, 3),
      duty_phrases=("Du bygger kurs fra behovskartlegging til gjennomføring.",),
      employers=("Kompetansesenteret", "Bransjeakademiet")),
    F("kommunikasjon", "offentlig",
      titles=("Kommunikasjonsrådgiver", "Innholdsprodusent", "SoMe-ansvarlig"),
      skills_core=("kommunikasjon", "innholdsproduksjon"),
      skills_extra=("formidling", "digital_laering", "pressehandtering"),
      norwegian_options=("C1",),
      work_modes=("onsite", "hybrid"),
      salary_band=(540_000, 650_000),
      min_years_options=(2, 3),
      duty_phrases=("Du gjør komplekst fagstoff forståelig for folk.",),
      employers=("Helseforetaket", "Direktoratet", "Energiselskapet kommunikasjon")),
    F("sosialarbeid", "offentlig",
      titles=("Sosialkonsulent", "Miljøterapeut", "Veileder NAV"),
      skills_core=("sosialt_arbeid", "saksbehandling"),
      norwegian_options=("C1",),
      shift_options=(("day",), ("day", "evening", "weekend")),
      salary_band=(500_000, 600_000),
      min_years_options=(0, 2),
      duty_phrases=("Oppfølging av mennesker i krevende livssituasjoner.",),
      employers=("NAV-kontoret", "Barnevernstjenesten", "Bofellesskapet")),
    F("grafisk", "kultur",
      titles=("Grafisk designer", "Visuell designer"),
      skills_core=("grafisk_design", "innholdsproduksjon"),
      skills_extra=("adobe-pakken", "profilarbeid", "figma"),
      norwegian_options=("B2", None),
      english_options=(None, "B2"),
      work_modes=("onsite", "hybrid", "remote"),
      salary_band=(500_000, 640_000),
      min_years_options=(2, 3),
      duty_phrases=("Visuelle identiteter og redaksjonell design for kunder.",),
      employers=("Designbyrået", "Mediehuset marked")),

    # ---------------- Havbruk / lab ----------------
    F("marinbiolog", "havbruk",
      titles=("Fiskehelsekonsulent", "Marinbiolog", "Miljørådgiver hav", "Fiskehelsebiolog"),
      skills_core=("fiskehelse", "feltarbeid"),
      skills_extra=("miljoovervaking", "gis", "r_statistikk", "laboratoriearbeid", "b-undersokelser"),
      cert_options=((), ("fiskehelsebiolog_autorisasjon",)),
      license_options=(None, "B"),
      norwegian_options=("B2",),
      work_modes=("onsite", "hybrid"),
      salary_band=(520_000, 660_000),
      overnight_choices=(False, True),
      min_years_options=(0, 2, 5),
      duty_phrases=("Anleggsbesøk, prøvetaking og rapportering langs kysten.",
                    "Nyutdannede med relevant master oppfordres til å søke."),
      employers=("Akvaservice", "Havmiljøkonsulentene", "Oppdrettskonsernet fagstab")),
    F("akvatekniker", "havbruk",
      titles=("Havbrukstekniker", "Røkter", "Driftstekniker sjø"),
      skills_core=("akvakultur_drift",),
      skills_extra=("fiskehelse", "feltarbeid", "batforerbevis"),
      license_options=(None, "B"),
      norwegian_options=("B1",),
      shift_options=(("day", "weekend"), ("day",)),
      salary_band=(460_000, 560_000),
      physical_options=(("heavy_lifting",),),
      overnight_choices=(False, True),
      min_years_options=(0, 1),
      duty_phrases=("Fôring, notarbeid og daglig tilsyn i all slags vær.",),
      employers=("Lakseoppdretteren", "Sjøanlegget drift")),
    F("labtekniker", "industri",
      titles=("Laboratorieingeniør", "Labtekniker", "Analytisk kjemiker"),
      skills_core=("laboratoriearbeid", "kvalitetssikring_ks"),
      skills_extra=("dataanalyse", "iso 17025", "provetaking"),
      norwegian_options=("B2",),
      salary_band=(490_000, 580_000),
      min_years_options=(0, 1, 2),
      duty_phrases=("Akkrediterte analyser med dokumentert kvalitet.",),
      employers=("Analyse-laboratoriet", "Næringsmiddellabben", "Miljølab Vest")),

    # ---------------- Logistikk / transport ----------------
    F("lager", "logistikk",
      titles=("Lagermedarbeider", "Truckfører lager", "Terminalarbeider"),
      skills_core=("lagerarbeid", "truckkjoring"),
      skills_extra=("wms_system", "plukk_pakk", "varemottak", "lastsikring"),
      cert_options=(("truckforerbevis_t1_t4",), ()),
      norwegian_options=("B1",),
      shift_options=(("day",), ("day", "evening"), ("night",), ("day", "evening", "night")),
      salary_band=(420_000, 520_000),
      physical_options=((), ("heavy_lifting",)),
      min_years_options=(0, 1, 2),
      duty_phrases=("Plukk, pakk og varemottak mot skanner i WMS.",
                    "Presisjon og tempo går hånd i hånd."),
      employers=("Distribusjonssenteret", "Grossistlageret", "Netthandelslageret", "Godsterminalen")),
    F("lager_leder", "logistikk",
      titles=("Teamleder lager", "Driftsleder logistikk", "Skiftleder terminal"),
      skills_core=("lagerarbeid", "teamledelse"),
      skills_extra=("wms_system", "opplaering_ansatte", "vaktplanlegging", "personalledelse"),
      norwegian_options=("B2",),
      shift_options=(("day", "evening"), ("day",), ("night",)),
      salary_band=(500_000, 600_000),
      min_years_options=(3, 5),
      duty_phrases=("Du leder skiftet og eier kvaliteten i vareflyten.",),
      employers=("Logistikkonsernet", "Tredjepartslogistikeren")),
    F("sjafor_ce", "transport",
      titles=("Distribusjonssjåfør CE", "Langtransportsjåfør", "Sjåfør vogntog"),
      skills_core=("sjafor_tungbil", "lastsikring"),
      skills_extra=("distribusjonskjoring", "ruteplanlegging", "adr-gods"),
      cert_options=(("ysk_gods",), ("ysk_gods", "adr_grunnkurs")),
      license_options=("CE", "C1"),
      norwegian_options=("B1",),
      shift_options=(("day",), ("day", "night"), ("day", "evening")),
      salary_band=(480_000, 620_000),
      overnight_choices=(False, True),
      min_years_options=(2, 3),
      duty_phrases=("Faste ruter med moderne bilpark.",
                    "Kjøre- og hviletid følges til punkt og prikke."),
      employers=("Transportkonsernet", "Mjøstransport", "Kysttransport")),
    F("sjafor_varebil", "transport",
      titles=("Varebilsjåfør", "Distribusjonssjåfør kl. B", "Budbilsjåfør"),
      skills_core=("distribusjonskjoring",),
      skills_extra=("ruteplanlegging", "varemottak", "kundeservice"),
      license_options=("B",),
      norwegian_options=("B1",),
      shift_options=(("day",), ("day", "evening")),
      salary_band=(430_000, 510_000),
      min_years_options=(0, 1, 2),
      duty_phrases=("Pakkelevering i faste soner — ingen YSK-krav under 3,5 tonn.",),
      employers=("Budselskapet", "Hjemleveringstjenesten")),
    F("bussjafor", "transport",
      titles=("Bussjåfør", "Sjåfør rutebuss"),
      skills_core=("persontransport", "kundeservice"),
      cert_options=(("ysk_person",),),
      license_options=("D",),
      norwegian_options=("B1",),
      shift_options=(("day", "evening", "weekend"), ("day",)),
      salary_band=(470_000, 540_000),
      min_years_options=(0, 2),
      duty_phrases=("Rutetrafikk med fokus på sikkerhet og service.",),
      employers=("Kollektivselskapet", "Busselskapet")),
    F("taxi", "transport",
      titles=("Taxisjåfør", "Sjåfør persontransport"),
      skills_core=("persontransport", "kundeservice"),
      cert_options=(("kjoreseddel_persontransport",),),
      license_options=("B",),
      norwegian_options=("B1",),
      shift_options=(("day", "evening"), ("day", "evening", "night", "weekend")),
      salary_band=(400_000, 520_000),
      min_years_options=(0, 2),
      duty_phrases=("Kjøring for faste og spontane kunder i hele byområdet.",),
      employers=("Taxisentralen", "Persontransport AS")),
    F("renovasjon", "transport",
      titles=("Renovasjonssjåfør", "Sjåfør komprimatorbil"),
      skills_core=("distribusjonskjoring",),
      skills_extra=("lastsikring", "ruteplanlegging"),
      cert_options=(("ysk_gods",),),
      license_options=("C",),
      norwegian_options=("B1",),
      salary_band=(470_000, 540_000),
      min_years_options=(2,),
      duty_phrases=("Faste henteruter med tidlig start og fri ettermiddag.",),
      employers=("Renovasjonsselskapet", "Gjenvinningskonsernet")),
]}


# Employers used when a family list runs dry; combined with city for variety.
GENERIC_EMPLOYER_STEMS = (
    "Nordvik Gruppen", "Fjellheim AS", "Brattli & Sønner", "Vestavind",
    "Solsiden Drift", "Kvitfjell Service", "Elvebredden", "Nordlys Partner",
    "Granittveien", "Sjøkanten Holding", "Bjørkelunden", "Myrvang Drift",
)
